---
common: 
  llm_model: 'microsoft/phi-2'
  embedding_model: 
    name: 'all-MiniLM-L6-v2.gguf2.f16.gguf'
    kwargs: 
      allow_download: True
  reranker_model: 'BAAI/bge-reranker-base'
  vectorstore:
    path: 'data/vectorstore/chromadb_512_32_all-MiniLM-L6-v2'
    k : 300
  compression_retriever_top_n: 9

data-ingest:
  textsplitter:
    chunk_size: 512
    overlap: 32
  documents: 
    path: 'data/rel18/'
    extensions: 
      - '*.docx'