LLM_MODEL_NAME='microsoft/phi-2'
EMBEDDING_MODEL_NAME='all-MiniLM-L6-v2.gguf2.f16.gguf'
# RERANKER_MODEL_NAME= 'BAAI/bge-reranker-base'
RERANKER_MODEL_NAME= 'BAAI/bge-reranker-base'
TEXTSPLITTER_CHUNK_SIZE = 512
TEXTSPLITTER_OVERLAP = 32
VECTOR_STORE_NAME = f'chromadb_{TEXTSPLITTER_CHUNK_SIZE}_{TEXTSPLITTER_OVERLAP}'
VECTOR_RETRIEVER_K =300
COMPRESSION_RETRIEVER_TOP_N = 9

GPU_NAMES = ['NVIDIA GeForce GTX 1080 Ti', 'NVIDIA GeForce GTX 1080 Ti (2)']
